### ISSUE TITLE
Parameter "Tuning_Bloom_Upsample_Spread" is not used

### ISSUE THREAD

**Issue by qarlosh** [MinorKeyGames/CRTSim#1]
On step 4 (upsampling) of the main `Render()` function, the parameter `Tuning_Bloom_Downsample_Spread` is used in the calculations instead of `Tuning_Bloom_Upsample_Spread`. Is this correct? (The default values of both parameters are `0.025f`, so it's not noticeable)

**Comment by PirateHearts** [comment]
Thanks for catching that, I'll get it fixed asap!
